### ISSUE TITLE
Problem with admin password when I start martini with martini-cli --server http://localhost/api connect

### ISSUE THREAD

**Issue by freediver2605** [VeeamHub/martini-cli#2]
Hi,

I'm not able to start the martini server.

It doesn't matter which passwort I use. I always got an authentication error.

Can I reset it or what can I do?
Can you help me with this?

Regards
Chris

cdo@ubuntu:~$ martini-cli --server http://localhost/api connect
Type in the admin password: 2020/03/31 03:26:18 Got error Authentication failed authenticating
2020/03/31 03:26:18 Authentication failed

cdo@ubuntu:~$ cat .martiniconfig
{"Server":"https://localhost/api","Token":"1011dcb4-5bb5-4b21-a818-dc277c66a49e","Renew":"","Lifetime":0,"Username":"admin","ServerSkew":0}cdo@ubuntu:~$

**Comment by tdewin** [comment]
Seems that ubuntu uses php 7.3 now and it does not pull the old version when installing. So not only do you need to install php but also other requirements:

sudo apt-get install php
sudo apt-get install php-xml
sudo apt-get install php-mysql
sudo composer --working-dir=/var/www/html install
sudo service apache2 restart

But that doesn't fix the problem yet with ubuntu. PHP 7.3 and mysql 8 have some weird issue with password authentication where mysql 8 defaults to a more secure password authentication system but PHP 7.3 does not support it. Trying to figure out the quick fix here.

**Comment by tdewin** [comment]
Ok to solve it for now until ubuntu gets PHP 7.4, please execute the previous command referenced:
> sudo apt-get install php
> sudo apt-get install php-xml
> sudo apt-get install php-mysql
> sudo composer --working-dir=/var/www/html install
> sudo service apache2 restart

Then login to the database (hopefully you have changed the root password)
> mysql -u root -p

And execute this alter statement to change the authentication mechanism. Make sure to use your existing martinidbo password
> ALTER USER 'martinidbo'@'localhost' IDENTIFIED WITH mysql_native_password BY 'mysupersecretpassword';

Let me know if this works for you

**Comment by freediver2605** [comment]
Hi,

I did all your commands, but I go the same error.

**Comment by tdewin** [comment]
Ok so you might have really forgotten the password. Here is a beta version where I quickly tried to fix all issues. http://dewin.me/martini/martini-cli-beta.zip

You can use it in 2 ways:
- Just start from scratch with this beta
- use the new reset password for admin on the existing setup (just have the 2 binaries side by side)
> martini-cli-beta setup --resetadmin 

Hopefully this helps

**Comment by freediver2605** [comment]
Hi,
thank you so much for helping me so deeply.
I'm so sorry but it didn't work with the beta too.
Shall I install another ubuntu version or maybe centos?

**Comment by tdewin** [comment]
Well I tested with ubuntu 18.04 LTS multiple times, so if you can try with that one and give me feedback. I'll try it out the newer one as well

**Comment by freediver2605** [comment]
Ok. I'll try tomorrow with all ubuntu version. ;-)

**Comment by tdewin** [comment]
Tried both today, both work with the beta.

Maybe also try the --verbose 1 parameter when doing the connect. It should tell you more on what's going on

**Comment by tdewin** [comment]
martini-cli-beta is now martini-cli and seems to work with ubuntu 20.04! Closing the case
