### ISSUE TITLE
Mysql config

### ISSUE THREAD

**Issue by charris-crs** [VeeamHub/martini-cli#3]
Ubuntu by default has root account disabled so this caused me a bit of a problem with:
mysql -u root -p

In the end I ran it as a different user but all seems to have come out OK.

Also the admin password requirement wasn't clear
It states "type in the admin password" might be better if it said "create admin password"
But I have it working.

Thanks

**Comment by tdewin** [comment]
Thanks for the feedback, of course the mysql setup might be different on your system. Reminds me that we need to retest it on the latest ubuntu version

**Comment by tdewin** [comment]
Updated the code to "Set the admin password". Next time a newer version is released/compiled, it will be updated!

Closing the issue now
